"""Targeted sequencing panels: what the assay could physically have seen.

Most tuberculosis sequencing in high-burden settings is targeted, not
whole-genome. Deeplex Myc-TB, AmpliSeq TB and similar panels amplify a fixed
set of loci, and a locus that is not on the panel was never amplified, never
sequenced, and cannot be called — no matter how deep the run was or what a
coverage file says about it.

Why this needs its own object rather than trusting the mask
-----------------------------------------------------------
``CallableMask`` answers "was this locus callable in this run?" and is the gate
that lets a drug reach SUSCEPTIBLE. That is the right gate for whole-genome
data, where every locus was at least attempted. On a targeted panel it is not
sufficient on its own, because a mask can be wrong in the one direction that
matters:

* a BED computed against a whole-genome reference lists every locus, including
  ones the panel never amplified;
* a depth table generated by a generic pipeline can report a locus as covered
  from off-target reads, stray mapping or barcode bleed;
* an engine adapter may supply per-gene QC for its full gene list rather than
  for the panel actually run.

In each case a drug whose locus was never on the panel could pass the callable
gate and reach SUSCEPTIBLE. That is the original defect of this codebase —
presuming a drug usable because nothing contradicted it — arriving through a
file rather than through a ``return True``.

So a panel is declared separately and **intersects** the mask: coverage for a
locus outside the panel is discarded and recorded as discarded. The panel is
the assay's physical limit; the mask is what that assay achieved within it.
Neither can substitute for the other, and the narrower of the two always wins.

What a panel does not do
------------------------
Being on the panel is not evidence of coverage. A declared locus with no mask
entry is still not callable — the panel says it *could* have been sequenced,
not that it *was*. Only the mask can say that, and it still has to.
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable, Optional

from ..core.models import LocusCoverage
from .callable_mask import CallableMask

#: Assay families this schema knows. A panel must say which it is, because the
#: limit of detection for minority alleles differs by chemistry and
#: ``modules/heteroresistance`` keys its floors on exactly these names.
ASSAY_KINDS = {"targeted-amplicon", "targeted-capture", "wgs"}


class PanelError(ValueError):
    """A panel declaration could not be read or is internally inconsistent."""


@dataclass(frozen=True)
class Panel:
    """The loci a targeted assay amplifies, declared by the laboratory.

    ``loci`` is the complete set the panel targets. It is supplied by whoever
    runs the assay, from the manufacturer's design, and is never inferred from
    observed coverage: inferring the panel from the data would make the panel
    agree with the data by construction and remove the check entirely.
    """

    name: str
    version: str
    assay: str
    source: str
    loci: frozenset[str] = frozenset()
    organism: Optional[str] = None
    reference_assembly: Optional[str] = None
    note: str = ""
    #: Has this locus list been checked against the manufacturer's own design
    #: document for the exact product and version in use? The bundled panels
    #: are reconstructed from published descriptions and ship ``False``.
    #:
    #: The distinction is safety-relevant in one direction. A panel that
    #: *under*-declares makes drugs NOT_ASSESSED, which is merely unhelpful. A
    #: panel that *over*-declares asserts the assay examined a locus it never
    #: amplified, and that assertion is what lets a drug reach SUSCEPTIBLE.
    #: An unverified list is therefore usable for development and refused for
    #: clinical reporting, exactly as the illustrative catalogue is.
    verified: bool = False

    def __post_init__(self) -> None:
        for attribute in ("name", "version", "assay", "source"):
            value = getattr(self, attribute)
            if not isinstance(value, str) or not value.strip():
                raise PanelError(f"panel requires {attribute}")
        if self.assay not in ASSAY_KINDS:
            raise PanelError(
                f"unknown assay kind {self.assay!r}; expected one of "
                f"{sorted(ASSAY_KINDS)}")
        if not self.loci:
            raise PanelError(
                f"panel {self.name} declares no loci. An empty panel would "
                f"make every drug NOT_ASSESSED, which is safe but useless; "
                f"an accidental empty list is more likely than an intended one")
        if not all(isinstance(locus, str) and locus.strip()
                   for locus in self.loci):
            raise PanelError("panel loci must be nonempty strings")

    @property
    def label(self) -> str:
        return f"{self.name} {self.version}"

    def covers(self, locus: str) -> bool:
        return locus in self.loci

    def missing_from(self, loci: Iterable[str]) -> list[str]:
        """Which of these loci the panel does not target."""
        return sorted(locus for locus in loci if locus not in self.loci)

    def supports_drug(self, required_loci: Iterable[str]) -> bool:
        """Can this panel support a susceptibility call for that drug at all?

        Every required locus must be on the panel. A partial panel cannot
        establish susceptibility: the resistance could be at the locus that was
        not amplified.
        """
        required = list(required_loci)
        return bool(required) and not self.missing_from(required)

    def describe(self) -> str:
        status = "verified" if self.verified else "UNVERIFIED locus list"
        return (f"{self.label} ({self.assay}, {len(self.loci)} locus/loci, "
                f"source {self.source}; {status})")

    @classmethod
    def from_dict(cls, payload: dict) -> "Panel":
        if not isinstance(payload, dict):
            raise PanelError("a panel declaration must be a JSON object")
        unknown = set(payload) - {
            "name", "version", "assay", "source", "loci", "organism",
            "reference_assembly", "note", "verified"}
        if unknown:
            raise PanelError(
                f"unknown panel field(s): {sorted(unknown)}. A misspelled "
                f"'loci' key would silently declare an empty panel")
        loci = payload.get("loci")
        if not isinstance(loci, (list, tuple, set, frozenset)):
            raise PanelError("panel 'loci' must be a list")
        return cls(
            name=payload.get("name", ""), version=payload.get("version", ""),
            assay=payload.get("assay", ""), source=payload.get("source", ""),
            loci=frozenset(loci), organism=payload.get("organism"),
            reference_assembly=payload.get("reference_assembly"),
            note=payload.get("note", ""),
            verified=bool(payload.get("verified", False)))

    @classmethod
    def load(cls, path: str | Path) -> "Panel":
        try:
            payload = json.loads(Path(path).read_text(encoding="utf-8"))
        except (OSError, ValueError) as exc:
            raise PanelError(f"could not read panel {path}: {exc}") from exc
        return cls.from_dict(payload)


@dataclass
class PanelRestriction:
    """What a panel removed from a mask, kept so a report can say so."""

    panel: Panel
    kept: list[str] = field(default_factory=list)
    discarded: list[str] = field(default_factory=list)

    @property
    def restricted(self) -> bool:
        return bool(self.discarded)

    def describe(self) -> str:
        if not self.discarded:
            return (f"{self.panel.label}: every mask locus is on the panel "
                    f"({len(self.kept)} locus/loci)")
        return (f"{self.panel.label}: discarded coverage for "
                f"{len(self.discarded)} locus/loci absent from the panel "
                f"({', '.join(self.discarded[:6])}"
                f"{', ...' if len(self.discarded) > 6 else ''}); a targeted "
                f"assay cannot call a locus it never amplified")


def restrict(mask: CallableMask, panel: Panel
             ) -> tuple[CallableMask, PanelRestriction]:
    """Intersect a callable mask with what the panel physically targets.

    Coverage claimed for a locus outside the panel is dropped, not trusted.
    Off-target reads, stray mapping and whole-genome BED files all produce
    exactly that claim, and acting on it would let a drug the assay never
    examined reach SUSCEPTIBLE.
    """
    kept: dict[str, LocusCoverage] = {}
    discarded: list[str] = []
    for locus in sorted(mask.loci):
        if panel.covers(locus):
            kept[locus] = mask.coverage_for(locus)
        else:
            discarded.append(locus)

    source = f"{mask.source} restricted to {panel.label}"
    restricted = CallableMask(kept, source=source)
    return restricted, PanelRestriction(panel=panel, kept=sorted(kept),
                                        discarded=discarded)


def off_panel_variants(panel: Panel, genes: Iterable[str]) -> list[str]:
    """Loci that carried a variant but which the panel says it does not target.

    A disagreement between the declaration and the data, and it is reported
    rather than acted on. Variants are deliberately **not** filtered by the
    panel: dropping a variant call at an undeclared locus would discard
    evidence of resistance, which is the one direction this system never moves
    in. If the panel is under-declared the variant is real and the declaration
    needs fixing; if the data came from a different assay than the panel
    describes, that is worth knowing before reading any of it.

    The check is one-sided by nature. An *over*-declared panel — one claiming
    loci the assay never amplified — produces no variants to notice, which is
    exactly why ``verified`` exists and why over-declaration is the dangerous
    direction.
    """
    return sorted({gene for gene in genes if gene and not panel.covers(gene)})


def unsupported_drugs(panel: Panel, required_loci_by_drug: dict[str, list[str]]
                      ) -> dict[str, list[str]]:
    """Drugs this panel cannot support, mapped to the loci it is missing.

    A report should name these explicitly rather than letting them appear as
    ordinary NOT_ASSESSED results: "this assay does not cover pyrazinamide" is
    a fact about the assay that a clinician can act on, where "not assessed" on
    its own reads like a run that went wrong.
    """
    unsupported = {}
    for drug, loci in sorted(required_loci_by_drug.items()):
        missing = panel.missing_from(loci)
        if missing or not loci:
            unsupported[drug] = missing
    return unsupported
